
CREATE SCHEMA IF NOT EXISTS `bd` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `bd` ;
CREATE TABLE Clientes (
    id_cliente INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100),
    email VARCHAR(100),
    telefono VARCHAR(20),
    fecha_registro DATE,
    saldo_actual DECIMAL(10, 2),
    categoria_riesgo VARCHAR(20)
);

CREATE TABLE Transacciones (
    id_transaccion INT PRIMARY KEY AUTO_INCREMENT,
    id_cliente INT,
    fecha_transaccion DATE,
    tipo_transaccion VARCHAR(50),
    monto DECIMAL(10, 2),
    categoria VARCHAR(50),
    FOREIGN KEY (id_cliente) REFERENCES Clientes(id_cliente)
);

-- Clientes --
INSERT INTO Clientes (nombre, email, telefono, fecha_registro, saldo_actual, categoria_riesgo) VALUES ('Laura Sanchez', 'laurasanchez83@hotmail.com', '9551056574', '2023-11-05', 2982.99, 'Bajo');
INSERT INTO Clientes (nombre, email, telefono, fecha_registro, saldo_actual, categoria_riesgo) VALUES ('Sofia Perez', 'sofiaperez79@outlook.com', '6245623213', '2023-10-28', 8447.4, 'Bajo');
INSERT INTO Clientes (nombre, email, telefono, fecha_registro, saldo_actual, categoria_riesgo) VALUES ('Carlos Martinez', 'carlosmartinez89@yahoo.com', '4298279076', '2023-12-27', 11131.25, 'Alto');
INSERT INTO Clientes (nombre, email, telefono, fecha_registro, saldo_actual, categoria_riesgo) VALUES ('Luis Torres', 'luistorres12@gmail.com', '6432234492', '2023-09-06', 12661.26, 'Alto');
INSERT INTO Clientes (nombre, email, telefono, fecha_registro, saldo_actual, categoria_riesgo) VALUES ('Diego Torres', 'diegotorres90@gmail.com', '3184807014', '2023-08-27', 9849.17, 'Bajo');

-- Transacciones --
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-13', 'Compra', 11594.66, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-25', 'Compra', 14137.84, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-16', 'Transferencia', 4066.91, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-05', 'Compra', 12077.3, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-04', 'Transferencia', 1556.05, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-15', 'Compra', 19185.79, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-01', 'Transferencia', 19628.23, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-23', 'Depósito', 8961.47, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-12', 'Transferencia', 142.53, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-31', 'Depósito', 10795.14, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-20', 'Depósito', 9578.3, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-29', 'Compra', 19994.66, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-06', 'Transferencia', 55.01, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-20', 'Transferencia', 4041.32, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-30', 'Pago', 6176.42, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-30', 'Pago', 8219.26, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-12', 'Compra', 2976.1, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-29', 'Depósito', 993.61, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-23', 'Depósito', 7843.22, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-04', 'Depósito', 1347.93, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-27', 'Compra', 18448.02, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-12', 'Transferencia', 4504.14, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-27', 'Transferencia', 13168.46, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-28', 'Transferencia', 15592.39, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-05', 'Pago', 13451.92, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-12', 'Compra', 10658.71, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-31', 'Depósito', 19936.11, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-22', 'Transferencia', 2330.57, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-12', 'Compra', 1388.39, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-25', 'Transferencia', 12515.61, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-10', 'Transferencia', 5282.6, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-29', 'Compra', 14711.26, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-06', 'Compra', 2070.12, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-25', 'Depósito', 4658.98, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-30', 'Depósito', 17419.42, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-22', 'Compra', 11647.68, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-14', 'Compra', 6564.9, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-14', 'Pago', 6548.76, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-18', 'Transferencia', 18254.0, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-29', 'Compra', 8249.24, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-28', 'Transferencia', 16632.25, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-09', 'Pago', 8656.8, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-21', 'Pago', 3750.79, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-29', 'Depósito', 11257.63, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-11', 'Pago', 7219.47, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-27', 'Transferencia', 4978.16, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-10', 'Transferencia', 3003.8, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-25', 'Depósito', 15009.37, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-24', 'Pago', 17651.08, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-07', 'Pago', 14862.68, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-19', 'Compra', 16572.79, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-30', 'Transferencia', 13850.08, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-24', 'Depósito', 8346.18, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-23', 'Compra', 10842.51, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-30', 'Depósito', 11870.55, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-27', 'Transferencia', 1468.63, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-22', 'Depósito', 166.78, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-10', 'Compra', 9583.37, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-07', 'Transferencia', 13068.08, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-17', 'Transferencia', 11258.17, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-12', 'Transferencia', 14321.33, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-17', 'Depósito', 12264.66, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-10', 'Pago', 16191.04, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-20', 'Pago', 16166.6, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-05', 'Transferencia', 3613.84, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-27', 'Depósito', 4567.15, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-12', 'Compra', 19096.73, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-28', 'Transferencia', 13580.98, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-21', 'Depósito', 5749.12, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-23', 'Depósito', 13588.22, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-12', 'Transferencia', 3647.71, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-30', 'Depósito', 9796.8, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-31', 'Transferencia', 4668.19, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-22', 'Pago', 6199.99, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-08', 'Compra', 19103.35, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-24', 'Compra', 5885.18, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-17', 'Pago', 7597.3, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-31', 'Compra', 8222.73, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-05', 'Depósito', 9003.75, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-03', 'Compra', 12259.06, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-03', 'Transferencia', 9707.6, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-03', 'Pago', 14038.41, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-05', 'Depósito', 14034.5, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-29', 'Transferencia', 18973.33, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-05', 'Compra', 14509.06, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-18', 'Pago', 13255.43, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-11', 'Compra', 14979.64, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-17', 'Transferencia', 5758.17, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-15', 'Transferencia', 15489.42, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-24', 'Depósito', 9375.08, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-10', 'Depósito', 12210.3, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-22', 'Compra', 11680.73, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-28', 'Transferencia', 16495.46, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-11', 'Transferencia', 16595.48, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-18', 'Depósito', 13293.84, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-07', 'Compra', 14036.62, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-08', 'Transferencia', 15778.55, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-06', 'Pago', 5742.66, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-28', 'Compra', 11115.09, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-08', 'Transferencia', 3937.46, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-16', 'Transferencia', 15079.22, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-22', 'Compra', 5603.36, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-22', 'Compra', 12284.31, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-27', 'Depósito', 15165.66, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-13', 'Compra', 8039.3, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-17', 'Depósito', 1488.77, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-24', 'Transferencia', 10045.24, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-14', 'Transferencia', 13396.7, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-28', 'Depósito', 10400.9, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-12', 'Transferencia', 7253.79, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-21', 'Pago', 5808.51, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-08', 'Compra', 5402.36, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-25', 'Compra', 11266.79, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-15', 'Depósito', 3578.56, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-03', 'Transferencia', 7078.29, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-12', 'Transferencia', 15264.24, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-02', 'Pago', 13102.59, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-20', 'Compra', 1741.99, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-24', 'Transferencia', 3803.73, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-04', 'Pago', 10502.25, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-18', 'Pago', 10893.79, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-23', 'Compra', 2344.69, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-22', 'Compra', 12485.14, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-23', 'Pago', 13830.14, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-10', 'Compra', 1140.32, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-28', 'Pago', 12820.24, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-02', 'Depósito', 2800.05, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-24', 'Depósito', 8261.79, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-19', 'Depósito', 8392.47, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-05', 'Transferencia', 14030.46, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-07', 'Compra', 8313.58, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-06', 'Transferencia', 19300.86, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-23', 'Pago', 2512.56, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-21', 'Compra', 2022.47, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-07', 'Pago', 5127.22, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-23', 'Depósito', 8600.78, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-16', 'Transferencia', 13387.3, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-13', 'Pago', 2074.94, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-10', 'Transferencia', 10831.85, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-04', 'Pago', 13582.69, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-26', 'Transferencia', 16330.06, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-23', 'Depósito', 4648.6, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-15', 'Compra', 9342.25, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-23', 'Transferencia', 18508.87, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-29', 'Compra', 12185.95, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-12', 'Pago', 1320.98, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-26', 'Depósito', 19138.63, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-01', 'Depósito', 13208.31, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-21', 'Pago', 43.56, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-31', 'Pago', 6155.64, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-03', 'Compra', 19945.8, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-31', 'Pago', 6853.59, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-08', 'Depósito', 15683.03, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-30', 'Transferencia', 16717.17, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-21', 'Depósito', 18891.67, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-16', 'Depósito', 4575.14, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-21', 'Depósito', 9015.0, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-02', 'Pago', 13760.65, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-11', 'Compra', 15519.96, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-08', 'Depósito', 16670.49, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-22', 'Compra', 10776.31, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-04', 'Transferencia', 15146.87, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-01', 'Transferencia', 1322.05, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-07', 'Compra', 5366.8, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-25', 'Compra', 1728.55, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-16', 'Depósito', 6436.85, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-27', 'Pago', 16120.56, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-15', 'Depósito', 14893.33, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-22', 'Depósito', 1990.68, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-03', 'Compra', 15716.56, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-26', 'Compra', 7985.27, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-03', 'Transferencia', 5342.75, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-23', 'Compra', 19010.91, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-30', 'Depósito', 1180.59, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-24', 'Pago', 10110.09, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-20', 'Pago', 4543.45, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-18', 'Transferencia', 3145.16, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-24', 'Pago', 8053.85, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-21', 'Transferencia', 8265.74, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-02', 'Compra', 16041.54, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-02', 'Transferencia', 17680.45, 'Finanzas');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-24', 'Transferencia', 12672.97, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-21', 'Transferencia', 8066.95, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-28', 'Transferencia', 1705.85, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-16', 'Transferencia', 85.77, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-20', 'Compra', 7672.74, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-17', 'Compra', 3442.49, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-11', 'Depósito', 17868.4, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-16', 'Pago', 15949.34, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-20', 'Transferencia', 3380.58, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-15', 'Depósito', 15068.3, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-31', 'Transferencia', 12559.97, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-19', 'Compra', 18298.97, 'Impuestos');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-14', 'Transferencia', 9592.09, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-25', 'Compra', 212.83, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-12', 'Depósito', 17569.93, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-28', 'Pago', 4185.38, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-10', 'Transferencia', 11214.55, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-15', 'Compra', 9467.97, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-23', 'Depósito', 764.16, 'Educación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-28', 'Pago', 8247.35, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-06', 'Depósito', 5797.89, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-17', 'Depósito', 7910.3, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-13', 'Transferencia', 17926.95, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-23', 'Transferencia', 2891.59, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-27', 'Compra', 12088.74, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-27', 'Depósito', 9380.15, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-09', 'Pago', 11563.39, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-08-17', 'Compra', 6299.7, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-31', 'Pago', 10967.64, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-14', 'Compra', 14121.32, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-21', 'Depósito', 18229.43, 'Transporte');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-31', 'Pago', 14005.44, 'Vivienda');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-29', 'Pago', 4221.64, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-16', 'Pago', 4004.46, 'Alimentación');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-19', 'Depósito', 5985.16, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-06', 'Compra', 14281.49, 'Ahorro');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-06', 'Transferencia', 11826.34, 'Servicios');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-02', 'Compra', 4217.93, 'Ropa');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-10-22', 'Compra', 17494.52, 'Comunicaciones');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-12-08', 'Compra', 1659.23, 'Entretenimiento');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-11-04', 'Pago', 10156.21, 'Salud');
INSERT INTO Transacciones (id_cliente, fecha_transaccion, tipo_transaccion, monto, categoria) VALUES (1, '2023-09-10', 'Pago', 8132.37, 'Servicios');
